tabMainTables <- 
  tabPanel("Tables",
           fluidRow(column(3,
                           selectInput("dataset", "Choose a dataset:",
                                       choices=c("Chromatin Maps"="maps", 
                                                 "SNPs"="snps", 
                                                 "Gene Expression"="genes"))),
                    column(2,
                           align="bottom",
                           br(),
                           downloadButton("downloadDataset", "Download", align="bottom"))
           ),
           h3(paste0("Chromatin Maps")),
           withSpinner(DT::dataTableOutput("mapsTable")),
           h3("SNPs"),
           withSpinner(DT::dataTableOutput("snpsTable")),
           h3("RNA-seq Expression"),
           selectInput("rnadb", "RNA-seq dataset",
                       choices=c("Adult Islets (Moran I, et al. 2012)"="moran",
                                 "Adult Islets - Cytokine-responsive expression (Ramos-Rodriguez M, et al. 2019)"="cytHI",
                                 "EndoC-bH1 - Cytokine-responsive expression (Ramos-Rodriguez M, et al. 2019)"="cytEndoC"),
                       width="600px"),
           withSpinner(DT::dataTableOutput("genesTable")),
           conditionalPanel(condition="input.rnadb!='moran'",
                            helpText("* DESeq2 normalized expression values"))
           )